module.exports = {
  projects: [
    '<rootDir>/apps/pollate-ng',
    '<rootDir>/apps/api',
    '<rootDir>/libs/data-access/question',
    '<rootDir>/libs/data-access/response',
    '<rootDir>/libs/data-access/chat',
    '<rootDir>/libs/data-access/user',
    '<rootDir>/libs/type/debate-builder',
    '<rootDir>/libs/type/debate-viewer',
    '<rootDir>/libs/api/feature/builder',
    '<rootDir>/libs/api/feature/viewer',
    '<rootDir>/libs/api/feature/question',
    '<rootDir>/libs/api/feature/user',
    '<rootDir>/libs/api/shared/gateway/question',
    '<rootDir>/libs/api/data-access/shared/util/mongoose',
    '<rootDir>/libs/api/shared/util/auth',
    '<rootDir>/libs/testing',
    '<rootDir>/libs/ng/state/question',
    '<rootDir>/libs/ng/builder',
    '<rootDir>/libs/ng/shared/environment',
    '<rootDir>/libs/api/shared/util/cache',
  ],
};
